---
title: "Brandon H. Ansbergs"
contact:
 phone: 360.281.9687
 linkedin: https://www.linkedin.com/in/brandon-ansbergs/
 email: Ans22004@byui.edu
---

## Education

**Brigham Young University-Idaho** (April 2023 - Current)  
BS, Computer Science  
Rexburg, ID

- GPA – 4.0
- Relevant Coursework: Programming w/Functions, Data Analytics and Intuition, Algorithmic Thinking, Cybersecurity, Web Fundamentals, Programming, Computer Systems

**Clark College** (March 2019)  
Associate of Arts Degree  
Vancouver, WA

## Tools

Python, Tableau, Linux, AWS, GitHub, Loom, Microsoft Office

## Academic Projects

**CSE 201 Programming with Functions**

- Demonstrated proficiency in Python programming, effectively utilizing libraries, external modules, and existing functions to enhance program capabilities for data analysis, testing, and data manipulation tasks, while adhering to established coding best practices for code clarity, readability, and maintainability.

**DS 150 Data Analytics and Intuition**

- Employed data cleansing techniques to merge nine data sources into a unified dataset of 62,047 lines and 81 variables, enabling comprehensive data analysis and subsequent presentation of findings through impactful Tableau visualizations.

**CSE 180 Algorithmic Thinking**

- Applied algorithmic concepts and theories to analyze and optimize various scenarios, including trip planning, graduation planning, and long-term goal planning.

## Work Experience

**Zumiez** (March 2022 – Sept 2023)  
Sales Associate, Vancouver, WA

- Exceeded sales goals each period, ranking in the top 25% of part time salespeople at my store.
- Mentored new sales associates and helped them to develop their sales skills and product knowledge.
- Demonstrated a commitment to teamwork by willingly stepping in to cover call-out shifts, ensuring the store's smooth operation.

**Safeway** (June 2022 – April 2023)  
Deli Clerk, Vancouver, WA

- Identified and eliminated process bottlenecks, resulting in a 15% increase in productivity, which allowed me to provide better customer service and support to my team.
- Ensured new food safety and sanitation procedures were implemented, resulting in a 100% passing rate on all food safety inspections.
- Volunteered to take on additional responsibilities, such as leading the deli team during busy periods when the manager wasn't available, or on days when the deli was short-staffed.

## Awards

Eagle Scout, Boy Scouts of America (Jan 2015)